### ISSUE TITLE
Empty List - Error when trying search functionality.

### ISSUE THREAD

**Issue by dreulavelle** [allyring/pvw#7]
I'm not very familiar with Go, but thought I'd post this here. 👍 

Just installed, ran for the first time. No list was populated. Tried the '/' to try some of the functionality. And it came with the error shown below. 

```bash
┌───────────────────────────┐
│ PID    Port   Status      │
│───────────────────────────│
│                           │
│                           │
│                           │
│                           │
│                           │
│                           │
│                           │
│                           │
│                           │
│                           │
└───────────────────────────┘
> type to search

↑/k move up      r refresh the list of processes    t terminate selected process    q quit
panic: runtime error: slice bounds out of range [1:0] toggle the search bar

goroutine 67 [running]:
main.parseLsof({0x0?, 0x0?}, {0x0, 0x0, 0x0, 0x0, {0xc00012a2a0, 0x3, 0x4}, {0x0, ...}, ...})
        /home/runner/work/pvw/pvw/main.go:337 +0xdf1
main.rerenderProcesses.func1()
        /home/runner/work/pvw/pvw/main.go:246 +0x7a
github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.0/tea.go:247 +0x38
created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.0/tea.go:246 +0x14d
```

**Comment by allyring** [comment]
Thanks for letting me know about this :) I've fixed this issue in v1.3.1 which I just released. Hope this helps, and let me know if you encounter any more issues :D
